spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://124.221.66.151:3306/minzu?useSSL=false'
    username: 123456
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0
